#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_HOST=root@192.168.2.101
readonly TARGET_PATH=/tmp/hellorust
readonly TARGET_ARCH=arm-unknown-linux-gnueabihf
#readonly TARGET_ARCH=armv7-unknown-linux-gnueabihf
readonly SOURCE_PATH=./target/${TARGET_ARCH}/release/dittorustcross


cargo build --release --target=${TARGET_ARCH}
#When cross-compiling, cargo does not use environment variables such as RUSTFLAGS,
#so following line is useless? Config can be applied in .cargo/config
#RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target=${TARGET_ARCH}
#cargo build --release --target=${TARGET_ARCH}
scp ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}

#connects to the target board over SSH and tries to run the binary we just copied there. 
#-t ensures that the command is terminatied when we hit ctrl-c in our terminal
ssh -t ${TARGET_HOST} ${TARGET_PATH}


