#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_HOST=root@192.168.2.101
readonly TARGET_PATH=/tmp/dittorustcross
#readonly TARGET_ARCH=arm-unknown-linux-gnueabihf
readonly TARGET_ARCH=arm-unknown-linux-gnueabihf
#readonly SOURCE_PATH=./target/release/hellorust
readonly SOURCE_PATH=./target/${TARGET_ARCH}/release/dittorustcross

#copy ditto libs so linker can find them
#cp ../libdittoffi.* target/arm-unknown-linux-gnueabihf/release/build/dittolive-ditto-sys-03c74983c2da6396/out/

#default target MUST be supplied here, so it can lookup the linker in  .cargo/conf?
LIBDITTO_STATIC=0 cargo build --release --target=${TARGET_ARCH}
scp ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}

#cp required lib to RPI4
scp ../libdittoffi.so ${TARGET_HOST}:/lib/

#connects to the target board over SSH and tries to run the binary we just copied there. 
#-t ensures that the command is terminatied when we hit ctrl-c in our terminal
ssh -t ${TARGET_HOST} ${TARGET_PATH}


